"""Tests for generator.cli_init module."""

import os
import copy
import tempfile

import pytest
import yaml

from generator.cli_init import (_arm_entry, _build_config, _detect_existing_config, _project_entry, _save_config,
                                _theme_section)
from generator.config import LEGACY_THEME, validate_config


@pytest.fixture
def essential():
    return {"username": "testuser", "name": "Test User", "tagline": "Hello World"}


@pytest.fixture
def arms():
    return [
        {"name": "Frontend", "items": ["React", "TypeScript"]},
        {"name": "Backend", "items": ["Python", "Node.js"]},
        {"name": "DevOps", "items": ["Docker", "AWS"]},
    ]


@pytest.fixture
def advanced():
    return {
        "bio": "A passionate developer.",
        "company": "Acme Corp",
        "location": "Earth",
        "philosophy": "Code is art.",
        "social": {"email": "test@example.com", "linkedin": "testuser"},
        "projects": [
            {"repo": "testuser/project-a", "arm": 0, "description": "Project A"},
        ],
        "stats": {"metrics": ["commits", "stars", "prs"]},
        "languages": {"exclude": ["HTML"], "max_display": 6},
    }


class TestBuildConfig:
    def test_build_config_minimal(self, essential, arms):
        config = _build_config(essential, arms, {})
        assert config["username"] == "testuser"
        assert config["profile"]["name"] == "Test User"
        assert config["profile"]["tagline"] == "Hello World"
        assert len(config["galaxy_arms"]) == 3
        assert config["galaxy_arms"][0]["name"] == "Frontend"
        assert "social" not in config
        assert "projects" not in config
        assert "theme" not in config

    def test_build_config_full(self, essential, arms, advanced):
        config = _build_config(essential, arms, advanced)
        assert config["username"] == "testuser"
        assert config["profile"]["bio"] == "A passionate developer."
        assert config["profile"]["company"] == "Acme Corp"
        assert config["profile"]["location"] == "Earth"
        assert config["profile"]["philosophy"] == "Code is art."
        assert config["social"]["email"] == "test@example.com"
        assert len(config["projects"]) == 1
        assert config["stats"]["metrics"] == ["commits", "stars", "prs"]
        assert config["languages"]["exclude"] == ["HTML"]
        assert config["languages"]["max_display"] == 6


class TestSaveConfig:
    def test_save_config_creates_file(self, essential, arms, monkeypatch):
        config = _build_config(essential, arms, {})
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_path = os.path.join(tmpdir, "config.yml")
            monkeypatch.setattr("generator.cli_init._CONFIG_PATH", tmp_path)

            result_path = _save_config(config)
            assert os.path.isfile(result_path)

            with open(result_path, "r") as f:
                content = f.read()
            assert "Generated by: python -m generator.main init" in content

            loaded = yaml.safe_load(content)
            assert loaded["username"] == "testuser"
            assert loaded["profile"]["name"] == "Test User"
            assert len(loaded["galaxy_arms"]) == 3


class TestDetectExistingConfig:
    def test_detect_existing_config_found(self, monkeypatch):
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_path = os.path.join(tmpdir, "config.yml")
            with open(tmp_path, "w") as f:
                yaml.dump({"username": "existing"}, f)

            monkeypatch.setattr("generator.cli_init._CONFIG_PATH", tmp_path)
            result = _detect_existing_config()
            assert result is not None
            assert result["username"] == "existing"

    def test_detect_existing_config_not_found(self, monkeypatch):
        monkeypatch.setattr(
            "generator.cli_init._CONFIG_PATH",
            "/nonexistent/path/config.yml",
        )
        result = _detect_existing_config()
        assert result is None


class TestConfigValidation:
    def test_config_passes_validation(self, essential, arms):
        config = _build_config(essential, arms, {})
        validated = validate_config(copy.deepcopy(config))
        assert validated["username"] == "testuser"
        assert validated["profile"]["name"] == "Test User"

    def test_full_config_passes_validation(self, essential, arms, advanced):
        config = _build_config(essential, arms, advanced)
        validated = validate_config(copy.deepcopy(config))
        assert validated["username"] == "testuser"
        assert validated["stats"]["metrics"] == ["commits", "stars", "prs"]


class TestLook:
    """Theme and motion, the questions the Atlas redesign added."""

    LOOK = {"dark": "cyanotype", "light": "deep-sky", "motion": False}

    def test_the_answers_are_written_as_theme_and_motion(self, essential, arms):
        config = _build_config(essential, arms, {}, self.LOOK)
        assert config["theme"] == {"dark": "cyanotype", "light": "deep-sky"}
        assert config["motion"] is False

    def test_the_result_validates_with_those_choices(self, essential, arms):
        validated = validate_config(_build_config(essential, arms, {}, self.LOOK))
        assert validated["themes"] == {"dark": "cyanotype", "light": "deep-sky", "overrides": {}}
        assert validated["motion"] is False

    def test_without_the_answers_nothing_is_written_and_the_defaults_apply(self, essential, arms):
        config = _build_config(essential, arms, {})
        assert "theme" not in config and "motion" not in config
        validated = validate_config(config)
        assert validated["themes"]["dark"] == "deep-sky" and validated["motion"] is True

    def test_a_colour_the_user_had_changed_is_kept(self):
        before = dict(LEGACY_THEME, void="#101820", synapse_cyan="#00FFEE")
        assert _theme_section("deep-sky", "cyanotype", before) == {
            "dark": "deep-sky", "light": "cyanotype", "void": "#101820", "synapse_cyan": "#00FFEE"}

    def test_the_nine_default_colours_of_version_one_are_not_written_again(self):
        assert _theme_section("deep-sky", "deep-sky", dict(LEGACY_THEME)) == {"dark": "deep-sky", "light": "deep-sky"}
        shouting = {key: value.upper() for key, value in LEGACY_THEME.items()}
        assert _theme_section("deep-sky", "deep-sky", shouting) == {"dark": "deep-sky", "light": "deep-sky"}

    def test_colours_that_no_longer_paint_anything_are_dropped(self):
        before = {"nebula": "#222222", "star_dust": "#333333", "void": "#101820"}
        assert _theme_section("deep-sky", "deep-sky", before) == {"dark": "deep-sky", "light": "deep-sky", "void": "#101820"}

    def test_an_old_theme_that_is_not_a_mapping_is_ignored(self):
        assert _theme_section("deep-sky", "deep-sky", None) == {"dark": "deep-sky", "light": "deep-sky"}
        assert _theme_section("deep-sky", "deep-sky", "blue") == {"dark": "deep-sky", "light": "deep-sky"}

    def test_a_config_with_kept_colours_validates_with_them_as_overrides(self, essential, arms):
        look = dict(self.LOOK, colours={"void": "#101820"})
        validated = validate_config(_build_config(essential, arms, {}, look))
        assert validated["themes"]["overrides"] == {"void": "#101820"}


class TestEntries:
    def test_an_arm_has_a_name_and_items_and_no_colour(self):
        assert _arm_entry("Backend", ["Python"], {"name": "Old", "color": "synapse_cyan", "items": ["Go"]}) == {
            "name": "Backend", "items": ["Python"]}

    def test_an_arm_keeps_the_repositories_pinned_to_it(self):
        assert _arm_entry("Backend", ["Python"], {"repos": ["engine"]}) == {
            "name": "Backend", "items": ["Python"], "repos": ["engine"]}

    def test_a_project_left_to_its_languages_has_no_arm(self):
        assert _project_entry("ada/engine", None, "Notes") == {"repo": "ada/engine", "description": "Notes"}

    def test_a_project_pinned_to_an_arm_says_which(self):
        assert _project_entry("ada/engine", 0, "Notes") == {"repo": "ada/engine", "arm": 0, "description": "Notes"}


class Each(list):
    """Answers to a question that is asked several times, in order."""


class Scripted:
    """Stands in for InquirerPy: every prompt answers from a script keyed by the start of its message.

    An unscripted prompt answers what pressing Enter would, and the stand-in is
    as strict as the library: a text default has to be a string, a list prompt
    starts with the choices marked as enabled (its `default` is not a list of
    selections), a select's default has to be one of its choices.
    """

    def __init__(self, answers):
        self.answers, self.asked = answers, []

    def _answer(self, message, enter):
        self.asked.append(message)
        for start, answer in self.answers.items():
            if message.startswith(start):
                enter = answer.pop(0) if isinstance(answer, Each) else answer
                break
        return type("Prompt", (), {"execute": lambda _self: enter})()

    @staticmethod
    def _values(choices):
        return [(c["value"], c.get("enabled", False)) if isinstance(c, dict) else
                (c.value, c.enabled) if hasattr(c, "value") else (c, False) for c in choices]

    def text(self, message="", default="", **_options):
        assert isinstance(default, str), f"text prompt {message!r} got a default that is not a string: {default!r}"
        return self._answer(message, default)

    def confirm(self, message="", default=False, **_options):
        assert isinstance(default, bool), f"confirm prompt {message!r} got default {default!r}"
        return self._answer(message, default)

    def select(self, message="", choices=(), default=None, **_options):
        values = [value for value, _enabled in self._values(choices)]
        assert default is None or default in values, f"select prompt {message!r}: {default!r} is not a choice"
        return self._answer(message, default if default in values else values[0])

    def fuzzy(self, message="", choices=(), default="", **_options):
        assert isinstance(default, str), f"fuzzy prompt {message!r}: default is the search text, not a selection"
        return self._answer(message, [value for value, enabled in self._values(choices) if enabled])

    def checkbox(self, message="", choices=(), **_options):
        return self._answer(message, [value for value, enabled in self._values(choices) if enabled])


class TestTheWholeWizard:
    def run(self, monkeypatch, tmp_path, answers, existing=None):
        from generator import cli_init
        path = tmp_path / "config.yml"
        if existing is not None:
            path.write_text(yaml.safe_dump(existing), encoding="utf-8")
        script = Scripted(answers)
        monkeypatch.setattr(cli_init, "inquirer", script)
        monkeypatch.setattr(cli_init, "_CONFIG_PATH", str(path))
        cli_init.run_init()
        return yaml.safe_load(path.read_text(encoding="utf-8")), script.asked

    BASE = {
        "GitHub username": "ada", "Display name": "Ada Lovelace", "Tagline": "Analyst",
        "Arm 1 name": "Engines", "Arm 2 name": "Notes", "Arm 3 name": "Looms",
        "Arm 1 technologies": ["Python"], "Arm 2 technologies": ["Markdown"], "Arm 3 technologies": ["Rust"],
        "Configure advanced": False, "Generate SVGs now": False,
    }

    def test_a_first_run_asks_for_palettes_and_motion_and_writes_a_valid_config(self, monkeypatch, tmp_path):
        answers = dict(self.BASE, **{"Palette for GitHub's dark": "cyanotype", "Palette for GitHub's light": "deep-sky",
                                     "Animate the images": False})
        config, asked = self.run(monkeypatch, tmp_path, answers)
        assert config["theme"] == {"dark": "cyanotype", "light": "deep-sky"} and config["motion"] is False
        assert [arm["name"] for arm in config["galaxy_arms"]] == ["Engines", "Notes", "Looms"]
        assert all("color" not in arm for arm in config["galaxy_arms"])
        assert not any("color" in question.lower() or "hex" in question.lower() for question in asked)
        validate_config(config)

    def test_editing_a_version_one_config_keeps_what_the_user_had_changed(self, monkeypatch, tmp_path, sample_config):
        existing = copy.deepcopy(sample_config)
        existing["theme"]["void"] = "#101820"
        existing["galaxy_arms"][0]["repos"] = ["nebula-ui"]
        answers = {"config.yml already exists": "edit", "Configure advanced": False, "Generate SVGs now": False}
        config, _asked = self.run(monkeypatch, tmp_path, answers, existing)
        assert config["theme"] == {"dark": "deep-sky", "light": "deep-sky", "void": "#101820"}
        assert config["motion"] is True
        assert config["galaxy_arms"][0] == {"name": "Frontend", "items": ["TypeScript", "React", "CSS"], "repos": ["nebula-ui"]}
        assert validate_config(config)["themes"]["overrides"] == {"void": "#101820"}

    def test_a_project_can_be_left_to_its_languages_or_pinned(self, monkeypatch, tmp_path):
        answers = dict(self.BASE, **{
            "Configure advanced": True, "Add a featured project": True, "Add another project": Each([True, False]),
            "Repository": Each(["ada/engine", "ada/notes"]), "Which arm": Each([None, 1]),
            "Short description": Each(["One", "Two"]),
            "Which stats": ["stars"], "Max languages": "5"})
        config, _asked = self.run(monkeypatch, tmp_path, answers)
        assert config["projects"] == [{"repo": "ada/engine", "description": "One"},
                                      {"repo": "ada/notes", "arm": 1, "description": "Two"}]
        validate_config(config)

    # ── editing keeps what the user had ──────────────────────────────────────

    EDIT = {"config.yml already exists": "edit", "Configure advanced": False, "Generate SVGs now": False}

    def test_editing_without_the_advanced_options_loses_nothing(self, monkeypatch, tmp_path, sample_config):
        existing = copy.deepcopy(sample_config)
        config, _asked = self.run(monkeypatch, tmp_path, dict(self.EDIT), existing)
        for section in ("social", "projects", "stats", "languages"):
            assert config[section] == existing[section], section
        assert config["profile"] == existing["profile"]
        assert [arm["items"] for arm in config["galaxy_arms"]] == [arm["items"] for arm in existing["galaxy_arms"]]
        validate_config(config)

    def test_editing_keeps_items_that_are_not_in_the_catalogue(self, monkeypatch, tmp_path, sample_config):
        existing = copy.deepcopy(sample_config)
        existing["galaxy_arms"][0]["items"] = ["TypeScript", "AWS / Oracle", "My Own Framework"]
        config, _asked = self.run(monkeypatch, tmp_path, dict(self.EDIT), existing)
        assert config["galaxy_arms"][0]["items"] == ["TypeScript", "AWS / Oracle", "My Own Framework"]

    def test_a_fourth_focus_area_and_the_projects_pinned_to_it_survive_an_edit(self, monkeypatch, tmp_path, sample_config):
        existing = copy.deepcopy(sample_config)
        existing["galaxy_arms"].append({"name": "Hardware", "items": ["Verilog"], "repos": ["fpga-toys"]})
        existing["projects"].append({"repo": "galaxy-dev/fpga-toys", "arm": 3, "description": "Blinking lights."})
        config, _asked = self.run(monkeypatch, tmp_path, dict(self.EDIT), existing)
        assert config["galaxy_arms"][3] == {"name": "Hardware", "items": ["Verilog"], "repos": ["fpga-toys"]}
        assert config["projects"][2]["arm"] == 3
        validate_config(config)

    def test_the_arm_of_a_project_can_be_any_of_the_arms_being_written(self, monkeypatch, tmp_path, sample_config):
        existing = copy.deepcopy(sample_config)
        existing["galaxy_arms"].append({"name": "Hardware", "items": ["Verilog"]})
        existing["projects"] = [{"repo": "galaxy-dev/fpga-toys", "arm": 3, "description": "Blinking lights."}]
        answers = dict(self.EDIT, **{"Configure advanced": True, "Add another project": False})
        config, _asked = self.run(monkeypatch, tmp_path, answers, existing)
        assert config["projects"] == [{"repo": "galaxy-dev/fpga-toys", "arm": 3, "description": "Blinking lights."}]
        validate_config(config)

    def test_editing_with_the_advanced_options_starts_from_what_was_there(self, monkeypatch, tmp_path, sample_config):
        existing = copy.deepcopy(sample_config)
        existing["stats"] = {"metrics": ["stars", "repos"]}
        existing["languages"] = {"exclude": ["HTML"], "max_display": 5}
        answers = dict(self.EDIT, **{"Configure advanced": True, "Add another project": Each([True, False])})
        config, _asked = self.run(monkeypatch, tmp_path, answers, existing)
        assert config["stats"] == {"metrics": ["stars", "repos"]}
        assert config["languages"] == {"exclude": ["HTML"], "max_display": 5}
        assert config["projects"] == [
            {"repo": "galaxy-dev/nebula-ui", "arm": 0, "description": "A component library."},
            {"repo": "galaxy-dev/stargate-api", "arm": 1, "description": "High-performance API gateway."}]
        assert config["social"] == existing["social"] and config["profile"] == existing["profile"]

    def test_an_answer_left_empty_in_the_advanced_options_removes_what_was_there(self, monkeypatch, tmp_path, sample_config):
        answers = dict(self.EDIT, **{"Configure advanced": True, "Company": "", "Email": "", "LinkedIn": "", "Website": "",
                                     "Add a featured project": False})
        config, _asked = self.run(monkeypatch, tmp_path, answers, copy.deepcopy(sample_config))
        assert "company" not in config["profile"] and "social" not in config and "projects" not in config
        assert config["profile"]["location"] == "San Francisco, CA"
        validate_config(config)

    def test_the_look_already_chosen_is_offered_again(self, monkeypatch, tmp_path, sample_config):
        existing = dict(copy.deepcopy(sample_config), motion=False)
        existing["theme"] = {"dark": "cyanotype", "light": "cyanotype"}
        config, _asked = self.run(monkeypatch, tmp_path, dict(self.EDIT), existing)
        assert config["theme"] == {"dark": "cyanotype", "light": "cyanotype"} and config["motion"] is False

    @pytest.mark.parametrize("typed, written", [("12", 12), ("0", 8), ("²", 8), ("-3", 8), ("many", 8), ("99", 20), (" 7 ", 7)])
    def test_the_number_of_languages_is_a_whole_number_in_range_whatever_is_typed(self, monkeypatch, tmp_path, typed, written):
        answers = dict(self.BASE, **{"Configure advanced": True, "Add a featured project": False, "Max languages": typed})
        config, _asked = self.run(monkeypatch, tmp_path, answers)
        assert config["languages"]["max_display"] == written
        validate_config(config)

    @pytest.mark.parametrize("odd", [
        {"profile": None}, {"profile": {"name": 2024, "tagline": None}}, {"galaxy_arms": None},
        {"galaxy_arms": ["Frontend", {"name": None, "items": None}]}, {"stats": None, "languages": None},
        {"theme": "blue"}, {"theme": {"dark": "neon"}}, {"projects": [None, {"repo": None, "arm": True}]},
        {"social": ["a", "list"]}, {"languages": {"exclude": "HTML", "max_display": "8"}},
    ])
    def test_an_existing_config_with_odd_values_is_editable_and_comes_out_valid(self, monkeypatch, tmp_path, sample_config, odd):
        existing = dict(copy.deepcopy(sample_config), **odd)
        answers = dict(self.BASE, **{"config.yml already exists": "edit", "Configure advanced": True,
                                     "Add a featured project": False})
        config, _asked = self.run(monkeypatch, tmp_path, answers, existing)
        validate_config(config)

    def test_a_config_that_cannot_be_read_is_not_replaced_without_asking(self, monkeypatch, tmp_path):
        from generator import cli_init
        path = tmp_path / "config.yml"
        path.write_text("username: [unclosed", encoding="utf-8")
        script = Scripted({"config.yml exists but could not be read": False})
        monkeypatch.setattr(cli_init, "inquirer", script)
        monkeypatch.setattr(cli_init, "_CONFIG_PATH", str(path))
        cli_init.run_init()
        assert path.read_text(encoding="utf-8") == "username: [unclosed"
        assert len(script.asked) == 1

    def test_a_config_that_cannot_be_read_is_replaced_when_the_user_says_so(self, monkeypatch, tmp_path):
        answers = dict(self.BASE, **{"config.yml exists but could not be read": True})
        from generator import cli_init
        path = tmp_path / "config.yml"
        path.write_text("username: [unclosed", encoding="utf-8")
        script = Scripted(answers)
        monkeypatch.setattr(cli_init, "inquirer", script)
        monkeypatch.setattr(cli_init, "_CONFIG_PATH", str(path))
        cli_init.run_init()
        assert validate_config(yaml.safe_load(path.read_text(encoding="utf-8")))["username"] == "ada"


def test_the_prompts_are_built_the_way_the_library_needs_them():
    """With the real library: what an edit offers is really preselected, and every text default is a string."""
    from InquirerPy import inquirer
    from generator import cli_init
    choices = cli_init._tech_choices(["Python", "Go"], ["Go", "AWS / Oracle", None, " "])
    prompt = inquirer.fuzzy(message="x", choices=choices, multiselect=True)
    assert [choice["value"] for choice in prompt.content_control.choices if choice["enabled"]] == ["Go", "AWS / Oracle"]
    assert [choice["value"] for choice in prompt.content_control.choices] == ["Go", "AWS / Oracle", "Python"]
    for value in (None, 2024, "text"):
        inquirer.text(message="x", default=cli_init._text(value))
